//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MMN.Util.Translation.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Traducoes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Traducoes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MMN.Util.Translation.Resources.Traducoes", typeof(Traducoes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assinatura Eletrônica Atualizada com Sucesso!.
        /// </summary>
        internal static string AssinaturaEletronicaAtualizada {
            get {
                return ResourceManager.GetString("AssinaturaEletronicaAtualizada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favor verificar sua caixa de email.
        /// </summary>
        internal static string AssinaturaEletronoicaEnviadaPorEmail {
            get {
                return ResourceManager.GetString("AssinaturaEletronoicaEnviadaPorEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sua conta ainda não está ativa pois o email de validação ainda não foi confirmado. Clique em confirmar no seu email para ativar sua conta. Verifique sua caixa de entrada e spam..
        /// </summary>
        internal static string Cadastro_EmailNaoConfirmado {
            get {
                return ResourceManager.GetString("Cadastro_EmailNaoConfirmado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O login digitado já está em uso, por favor, digite outro login..
        /// </summary>
        internal static string Cadastro_LoginEmUso {
            get {
                return ResourceManager.GetString("Cadastro_LoginEmUso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login com caractéres inválidos, só é permitido letras e números..
        /// </summary>
        internal static string Cadastro_LoginInvalidoCaracter {
            get {
                return ResourceManager.GetString("Cadastro_LoginInvalidoCaracter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Um email de confirmação foi reenviado, clique para ativar sua conta. Verifique sua caixa de entrada ou pasta de spam..
        /// </summary>
        internal static string Cadastro_ReenviarEmailConfirmacao {
            get {
                return ResourceManager.GetString("Cadastro_ReenviarEmailConfirmacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patrocinador não encontrado..
        /// </summary>
        internal static string Cadastro_UsuarioPaiNaoEncontrado {
            get {
                return ResourceManager.GetString("Cadastro_UsuarioPaiNaoEncontrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cursos de &lt;span class=&quot;destaque&quot;&gt;nível avançado semi presencial&lt;span&gt;.
        /// </summary>
        internal static string Categoria_avancado {
            get {
                return ResourceManager.GetString("Categoria_avancado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cursos de &lt;span class=&quot;destaque&quot;&gt;nível básico&lt;span&gt;.
        /// </summary>
        internal static string Categoria_basico {
            get {
                return ResourceManager.GetString("Categoria_basico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cursos de &lt;span class=&quot;destaque&quot;&gt;nível intermediário&lt;span&gt;.
        /// </summary>
        internal static string Categoria_intermediario {
            get {
                return ResourceManager.GetString("Categoria_intermediario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe o numero do celular.
        /// </summary>
        internal static string CelularRequirido {
            get {
                return ResourceManager.GetString("CelularRequirido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não é possível fazer upgrade para um produto menor ou igual ao seu produto ativo..
        /// </summary>
        internal static string Compra_ErroUpgradeProdutoMenor {
            get {
                return ResourceManager.GetString("Compra_ErroUpgradeProdutoMenor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Os Dados do Usuário foram Atualizado com Sucesso!.
        /// </summary>
        internal static string DadosUsuarioAtualizado {
            get {
                return ResourceManager.GetString("DadosUsuarioAtualizado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cadastro finalizado!.
        /// </summary>
        internal static string DadosUsuarioSalvo {
            get {
                return ResourceManager.GetString("DadosUsuarioSalvo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dados do Usuario Atualizado com Sucesso!.
        /// </summary>
        internal static string DadosUsuariosSalvo {
            get {
                return ResourceManager.GetString("DadosUsuariosSalvo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Endereço Atualizado com Sucesso!.
        /// </summary>
        internal static string EditarEnderecoSalvo {
            get {
                return ResourceManager.GetString("EditarEnderecoSalvo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Inválido.
        /// </summary>
        internal static string EmailInvalido {
            get {
                return ResourceManager.GetString("EmailInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favor verificar sua caixa de email para redefinir sua senha..
        /// </summary>
        internal static string EnvioEmailEsqueciMinhaSenha {
            get {
                return ResourceManager.GetString("EnvioEmailEsqueciMinhaSenha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro ao alterar senha!.
        /// </summary>
        internal static string ErroAlterarSenha {
            get {
                return ResourceManager.GetString("ErroAlterarSenha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sua assinatura eletônica está incorreta. Verifique e digite novamente, ou vá no menu Meus Dados e gere uma nova..
        /// </summary>
        internal static string ErroAssinaturaEletronicaIncorreta {
            get {
                return ResourceManager.GetString("ErroAssinaturaEletronicaIncorreta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro em Atualizar Assinatura Eletrônica!.
        /// </summary>
        internal static string ErroAtualizarAssinaturaEletronica {
            get {
                return ResourceManager.GetString("ErroAtualizarAssinaturaEletronica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro ao atualizar usuário!.
        /// </summary>
        internal static string ErroAtualizarUsuario {
            get {
                return ResourceManager.GetString("ErroAtualizarUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro em Atualizar Imgem!.
        /// </summary>
        internal static string ErroImageAtualizada {
            get {
                return ResourceManager.GetString("ErroImageAtualizada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro ao Atualizar Endereço!.
        /// </summary>
        internal static string ErroSalvarEndereco {
            get {
                return ResourceManager.GetString("ErroSalvarEndereco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O formulário não está válido.
        /// </summary>
        internal static string FormularioRequerido {
            get {
                return ResourceManager.GetString("FormularioRequerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imagem Atualizada com Sucesso!.
        /// </summary>
        internal static string ImageAtualizada {
            get {
                return ResourceManager.GetString("ImageAtualizada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário bloqueado!.
        /// </summary>
        internal static string LoginBloqueado {
            get {
                return ResourceManager.GetString("LoginBloqueado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário inativo!.
        /// </summary>
        internal static string LoginInativo {
            get {
                return ResourceManager.GetString("LoginInativo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O login está em uso!.
        /// </summary>
        internal static string LoginIndisponivel {
            get {
                return ResourceManager.GetString("LoginIndisponivel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário ou Senha incorreto.
        /// </summary>
        internal static string LoginNaoEncontrado {
            get {
                return ResourceManager.GetString("LoginNaoEncontrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe o Nome.
        /// </summary>
        internal static string NomeRequirido {
            get {
                return ResourceManager.GetString("NomeRequirido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patrocinador Inválido!.
        /// </summary>
        internal static string PatrocinadorInvalido {
            get {
                return ResourceManager.GetString("PatrocinadorInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe o Patrocinador.
        /// </summary>
        internal static string PatrocinadorRequirido {
            get {
                return ResourceManager.GetString("PatrocinadorRequirido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senha deve conter no mínimo 8 caracteres sendo pelo menos 1 digito e 1 letra..
        /// </summary>
        internal static string RequisitosSenha {
            get {
                return ResourceManager.GetString("RequisitosSenha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assinatura Eletrônica requerida!.
        /// </summary>
        internal static string SemAssinaturaEletronica {
            get {
                return ResourceManager.GetString("SemAssinaturaEletronica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imagem requirida!.
        /// </summary>
        internal static string SemImagem {
            get {
                return ResourceManager.GetString("SemImagem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senha Inválida!.
        /// </summary>
        internal static string SenhaInvalida {
            get {
                return ResourceManager.GetString("SenhaInvalida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senhas não confere!.
        /// </summary>
        internal static string SenhasNaoConfere {
            get {
                return ResourceManager.GetString("SenhasNaoConfere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senha Alterada com sucesso!.
        /// </summary>
        internal static string SucessoAlterarSenha {
            get {
                return ResourceManager.GetString("SucessoAlterarSenha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login deve conter no mínimo 5 caracteres..
        /// </summary>
        internal static string TamanhoMinimoLogin {
            get {
                return ResourceManager.GetString("TamanhoMinimoLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Este é um teste.
        /// </summary>
        internal static string Teste {
            get {
                return ResourceManager.GetString("Teste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O Token expirou..
        /// </summary>
        internal static string TokenInvalido {
            get {
                return ResourceManager.GetString("TokenInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário não encontrado!.
        /// </summary>
        internal static string UsuarioNaoEncontrado {
            get {
                return ResourceManager.GetString("UsuarioNaoEncontrado", resourceCulture);
            }
        }
    }
}
