using MMN.Util.Util;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MMN.Api.Helpers
{
    public class ImagemHelper
    {
        private static readonly Dictionary<string, string> urlLojas = new Dictionary<string, string>
        {
            { "A.Brand", "https://bigcash.blob.core.windows.net/logos-empresas/A.Brand.jpg" },
            { "Acer", "https://bigcash.blob.core.windows.net/logos-empresas/Acer.jpg" },
            { "Allianz Travel", "https://bigcash.blob.core.windows.net/logos-empresas/Allianz Travel.jpg" },
            { "Almundo", "https://bigcash.blob.core.windows.net/logos-empresas/Almundo.jpg" },
            { "Amaro", "https://bigcash.blob.core.windows.net/logos-empresas/Amaro.jpg" },
            { "Animale", "https://bigcash.blob.core.windows.net/logos-empresas/Animale.jpg" },
            { "Apostilas Solucao", "https://bigcash.blob.core.windows.net/logos-empresas/Apostilas Solucao.jpg" },
            { "Asus", "https://bigcash.blob.core.windows.net/logos-empresas/Asus.jpg" },
            { "Azaleia", "https://bigcash.blob.core.windows.net/logos-empresas/Azaleia.jpg" },
            { "Babbel", "https://bigcash.blob.core.windows.net/logos-empresas/Babbel.jpg" },
            { "Bee Fitness", "https://bigcash.blob.core.windows.net/logos-empresas/Bee Fitness.jpg" },
            { "Bel Air", "https://bigcash.blob.core.windows.net/logos-empresas/Bel Air.jpg" },
            { "Bigbus", "https://bigcash.blob.core.windows.net/logos-empresas/Bigbus.jpg" },
            { "Boa Saude Suplementos", "https://bigcash.blob.core.windows.net/logos-empresas/Boa Saude Suplementos.jpg" },
            { "Brastemp", "https://bigcash.blob.core.windows.net/logos-empresas/Brastemp.jpg" },
            { "BringIT", "https://bigcash.blob.core.windows.net/logos-empresas/BringIT.jpg" },
            { "Britania", "https://bigcash.blob.core.windows.net/logos-empresas/Britania.jpg" },
            { "Camicado", "https://bigcash.blob.core.windows.net/logos-empresas/Camicado.jpg" },
            { "Carrefour", "https://bigcash.blob.core.windows.net/logos-empresas/Carrefour.jpg" },
            { "Carsystem", "https://bigcash.blob.core.windows.net/logos-empresas/Carsystem.jpg" },
            { "Casa das Aliancas", "https://bigcash.blob.core.windows.net/logos-empresas/Casa das Aliancas.jpg" },
            { "Casa Show", "https://bigcash.blob.core.windows.net/logos-empresas/Casa Show.jpg" },
            { "CCleaner", "https://bigcash.blob.core.windows.net/logos-empresas/CCleaner.jpg" },
            { "Centauro", "https://bigcash.blob.core.windows.net/logos-empresas/Centauro.jpg" },
            { "Central Ar", "https://bigcash.blob.core.windows.net/logos-empresas/Central Ar.jpg" },
            { "Clickbus", "https://bigcash.blob.core.windows.net/logos-empresas/Clickbus.jpg" },
            { "Compra Certa", "https://bigcash.blob.core.windows.net/logos-empresas/Compra Certa.jpg" },
            { "Consul", "https://bigcash.blob.core.windows.net/logos-empresas/Consul.jpg" },
            { "Conta Azul", "https://bigcash.blob.core.windows.net/logos-empresas/Conta Azul.jpg" },
            { "Contem 1g", "https://bigcash.blob.core.windows.net/logos-empresas/Contem 1g.jpg" },
            { "Continental", "https://bigcash.blob.core.windows.net/logos-empresas/Continental.jpg" },
            { "Corpo Ideal", "https://bigcash.blob.core.windows.net/logos-empresas/Corpo Ideal.jpg" },
            { "Corpo Perfeito", "https://bigcash.blob.core.windows.net/logos-empresas/Corpo Perfeito.jpg" },
            { "Decathlon", "https://bigcash.blob.core.windows.net/logos-empresas/Decathlon.jpg" },
            { "Decolar", "https://bigcash.blob.core.windows.net/logos-empresas/Decolar.jpg" },
            { "Dentro da historia", "https://bigcash.blob.core.windows.net/logos-empresas/Dentro-da-hist.jpg" },
            { "Drogaria Araujo", "https://bigcash.blob.core.windows.net/logos-empresas/Drogaria_Araujo_Logomarca.jpg" },
            { "Elet", "https://bigcash.blob.core.windows.net/logos-empresas/Elet.jpg" },
            { "EMBELLEZE", "https://bigcash.blob.core.windows.net/logos-empresas/EMBELLEZE.jpg" },
            { "Fastshop", "https://bigcash.blob.core.windows.net/logos-empresas/Fastshop.jpg" },
            { "Flydubai", "https://bigcash.blob.core.windows.net/logos-empresas/Flydubai.jpg" },
            { "Fotoregistro", "https://bigcash.blob.core.windows.net/logos-empresas/Fotoregistro.jpg" },
            { "Foxton", "https://bigcash.blob.core.windows.net/logos-empresas/Foxton.jpg" },
            { "Gigante-da-colina", "https://bigcash.blob.core.windows.net/logos-empresas/Gigante-da-colina.jpg" },
            { "Go daddy", "https://bigcash.blob.core.windows.net/logos-empresas/Go daddy.jpg" },
            { "Iberia", "https://bigcash.blob.core.windows.net/logos-empresas/Iberia.jpg" },
            { "Intershopp", "https://bigcash.blob.core.windows.net/logos-empresas/Intershopp.jpg" },
            { "Iugu", "https://bigcash.blob.core.windows.net/logos-empresas/Iugu.jpg" },
            { "Lança-perfume", "https://bigcash.blob.core.windows.net/logos-empresas/Lança-perfume.jpg" },
            { "Latam", "https://bigcash.blob.core.windows.net/logos-empresas/Latam.jpg" },
            { "Locaweb", "https://bigcash.blob.core.windows.net/logos-empresas/Locaweb.jpg" },
            { "Lufthansa", "https://bigcash.blob.core.windows.net/logos-empresas/Lufthansa.jpg" },
            { "Madrugao", "https://bigcash.blob.core.windows.net/logos-empresas/Madrugao.jpg" },
            { "Mobly", "https://bigcash.blob.core.windows.net/logos-empresas/Mobly.jpg" },
            { "Morena-Rosa", "https://bigcash.blob.core.windows.net/logos-empresas/Morena-Rosa.jpg" },
            { "Motorola", "https://bigcash.blob.core.windows.net/logos-empresas/Motorola.jpg" },
            { "NEscafé", "https://bigcash.blob.core.windows.net/logos-empresas/NEscafé.jpg" },
            { "Nespresso", "https://bigcash.blob.core.windows.net/logos-empresas/Nespresso.jpg" },
            { "avast", "https://bigcash.blob.core.windows.net/logos-empresas/avast.jpg" },
            { "avg", "https://bigcash.blob.core.windows.net/logos-empresas/avg.jpg" },
            { "drogaria liviero", "https://bigcash.blob.core.windows.net/logos-empresas/drogaria liviero.jpg" },
            { "drogaria-pacheco", "https://bigcash.blob.core.windows.net/logos-empresas/drogaria-pacheco.jpg" },
            { "dudalina", "https://bigcash.blob.core.windows.net/logos-empresas/dudalina.jpg" },
            { "duloren", "https://bigcash.blob.core.windows.net/logos-empresas/duloren.jpg" },
            { "eclock", "https://bigcash.blob.core.windows.net/logos-empresas/eclock.jpg" },
            { "edestinos", "https://bigcash.blob.core.windows.net/logos-empresas/edestinos.jpg" },
            { "eVitamins", "https://bigcash.blob.core.windows.net/logos-empresas/eVitamins.jpg" },
            { "Netshoes", "https://bigcash.blob.core.windows.net/logos-empresas/Netshoes.jpg" },
            { "Nextel", "https://bigcash.blob.core.windows.net/logos-empresas/Nextel.jpg" },
            { "Ovelha-negra", "https://bigcash.blob.core.windows.net/logos-empresas/Ovelha-negra.jpg" },
            { "Petitebox", "https://bigcash.blob.core.windows.net/logos-empresas/Petitebox.jpg" },
            { "Philco", "https://bigcash.blob.core.windows.net/logos-empresas/Philco.jpg" },
            { "Poderoso-tim╞o", "https://bigcash.blob.core.windows.net/logos-empresas/Poderoso-tim╞o.jpg" },
            { "Polishop", "https://bigcash.blob.core.windows.net/logos-empresas/Polishop.jpg" },
            { "Qatar", "https://bigcash.blob.core.windows.net/logos-empresas/Qatar.jpg" },
            { "Rede-perfumaria", "https://bigcash.blob.core.windows.net/logos-empresas/Rede-perfumaria.jpg" },
            { "Rentcars", "https://bigcash.blob.core.windows.net/logos-empresas/Rentcars.jpg" },
            { "Ri-happy", "https://bigcash.blob.core.windows.net/logos-empresas/Ri-happy.jpg" },
            { "Sao-paulo", "https://bigcash.blob.core.windows.net/logos-empresas/Sao-paulo.jpg" },
            { "Shoptime", "https://bigcash.blob.core.windows.net/logos-empresas/Shoptime.jpg" },
            { "Skinceuticals", "https://bigcash.blob.core.windows.net/logos-empresas/Skinceuticals.jpg" },
            { "Tag", "https://bigcash.blob.core.windows.net/logos-empresas/Tag.jpg" },
            { "Tokstok", "https://bigcash.blob.core.windows.net/logos-empresas/Tokstok.jpg" },
            { "Tripadvisor", "https://bigcash.blob.core.windows.net/logos-empresas/Tripadvisor.jpg" },
            { "Trocafone", "https://bigcash.blob.core.windows.net/logos-empresas/Trocafone.jpg" },
            { "Under-armour", "https://bigcash.blob.core.windows.net/logos-empresas/Under-armour.jpg" },
            { "Voopter", "https://bigcash.blob.core.windows.net/logos-empresas/Voopter.jpg" },
            { "Webcontinental", "https://bigcash.blob.core.windows.net/logos-empresas/Webcontinental.jpg" },
            { "edreams", "https://bigcash.blob.core.windows.net/logos-empresas/edreams.jpg" },
            { "elens", "https://bigcash.blob.core.windows.net/logos-empresas/elens.jpg" },
            { "englishtown", "https://bigcash.blob.core.windows.net/logos-empresas/englishtown.jpg" },
            { "eotica", "https://bigcash.blob.core.windows.net/logos-empresas/eotica.jpg" },
            { "estrela10", "https://bigcash.blob.core.windows.net/logos-empresas/estrela10.jpg" },
            { "farm", "https://bigcash.blob.core.windows.net/logos-empresas/farm.jpg" },
            { "futfanatics", "https://bigcash.blob.core.windows.net/logos-empresas/futfanatics.jpg" },
            { "fyi", "https://bigcash.blob.core.windows.net/logos-empresas/fyi.jpg" },
            { "gallerist", "https://bigcash.blob.core.windows.net/logos-empresas/gallerist.jpg" },
            { "girafa", "https://bigcash.blob.core.windows.net/logos-empresas/girafa.jpg" },
            { "giuliana-flores", "https://bigcash.blob.core.windows.net/logos-empresas/giuliana-flores.jpg" },
            { "gocase", "https://bigcash.blob.core.windows.net/logos-empresas/gocase.jpg" },
            { "greenman", "https://bigcash.blob.core.windows.net/logos-empresas/greenman.jpg" },
            { "jequiti", "https://bigcash.blob.core.windows.net/logos-empresas/jequiti.jpg" },
            { "kitchenaid", "https://bigcash.blob.core.windows.net/logos-empresas/kitchenaid.jpg" },
            { "kutiz", "https://bigcash.blob.core.windows.net/logos-empresas/kutiz.jpg" },
            { "lacaweb", "https://bigcash.blob.core.windows.net/logos-empresas/lacaweb.jpg" },
            { "lojas-colombo", "https://bigcash.blob.core.windows.net/logos-empresas/lojas-colombo.jpg" },
            { "malwee", "https://bigcash.blob.core.windows.net/logos-empresas/malwee.jpg" },
            { "marabras", "https://bigcash.blob.core.windows.net/logos-empresas/marabras.jpg" },
            { "marcyn", "https://bigcash.blob.core.windows.net/logos-empresas/marcyn.jpg" },
            { "marisa", "https://bigcash.blob.core.windows.net/logos-empresas/marisa.jpg" },
            { "metlife", "https://bigcash.blob.core.windows.net/logos-empresas/metlife.jpg" },
            { "nicephotos", "https://bigcash.blob.core.windows.net/logos-empresas/nicephotos.jpg" },
            { "nike", "https://bigcash.blob.core.windows.net/logos-empresas/nike.jpg" },
            { "nuuvem", "https://bigcash.blob.core.windows.net/logos-empresas/nuuvem.jpg" },
            { "offpremium", "https://bigcash.blob.core.windows.net/logos-empresas/offpremium.jpg" },
            { "olympikus", "https://bigcash.blob.core.windows.net/logos-empresas/olympikus.jpg" },
            { "onofre-eletro", "https://bigcash.blob.core.windows.net/logos-empresas/onofre-eletro.jpg" },
            { "onofre", "https://bigcash.blob.core.windows.net/logos-empresas/onofre.jpg" },
            { "pagseguro", "https://bigcash.blob.core.windows.net/logos-empresas/pagseguro.jpg" },
            { "phooto", "https://bigcash.blob.core.windows.net/logos-empresas/phooto.jpg" },
            { "pilao", "https://bigcash.blob.core.windows.net/logos-empresas/pila╠âo.jpg" },
            { "plantei", "https://bigcash.blob.core.windows.net/logos-empresas/plantei.jpg" },
            { "pompeia", "https://bigcash.blob.core.windows.net/logos-empresas/pompeia.jpg" },
            { "positivo", "https://bigcash.blob.core.windows.net/logos-empresas/positivo.jpg" },
            { "posthaus", "https://bigcash.blob.core.windows.net/logos-empresas/posthaus.jpg" },
            { "puket", "https://bigcash.blob.core.windows.net/logos-empresas/puket.jpg" },
            { "queropassagem", "https://bigcash.blob.core.windows.net/logos-empresas/queropassagem.jpg" },
            { "renner", "https://bigcash.blob.core.windows.net/logos-empresas/renner.jpg" },
            { "sald╞o", "https://bigcash.blob.core.windows.net/logos-empresas/sald╞o.jpg" },
            { "santosstore", "https://bigcash.blob.core.windows.net/logos-empresas/santosstore.jpg" },
            { "sem-parar", "https://bigcash.blob.core.windows.net/logos-empresas/sem-parar.jpg" },
            { "sEPHORA", "https://bigcash.blob.core.windows.net/logos-empresas/sEPHORA.jpg" },
            { "sestini", "https://bigcash.blob.core.windows.net/logos-empresas/sestini.jpg" },
            { "shoestock", "https://bigcash.blob.core.windows.net/logos-empresas/shoestock.jpg" },
            { "shop2gether", "https://bigcash.blob.core.windows.net/logos-empresas/shop2gether.jpg" },
            { "shopcruzeiro", "https://bigcash.blob.core.windows.net/logos-empresas/shopcruzeiro.jpg" },
            { "telhanorte", "https://bigcash.blob.core.windows.net/logos-empresas/telhanorte.jpg" },
            { "unidas aluguel", "https://bigcash.blob.core.windows.net/logos-empresas/unidas aluguel.jpg" },
            { "unidas livre", "https://bigcash.blob.core.windows.net/logos-empresas/unidas livre.jpg" },
            { "vaio", "https://bigcash.blob.core.windows.net/logos-empresas/vaio.jpg" },
            { "verisure", "https://bigcash.blob.core.windows.net/logos-empresas/verisure.jpg" },
            { "viajanet", "https://bigcash.blob.core.windows.net/logos-empresas/viajanet.jpg" },
            { "vinho-facil", "https://bigcash.blob.core.windows.net/logos-empresas/vinho-facil.jpg" },
            { "virtual-joias", "https://bigcash.blob.core.windows.net/logos-empresas/virtual-joias.jpg" },
            { "vivara", "https://bigcash.blob.core.windows.net/logos-empresas/vivara.jpg" },
            { "wine", "https://bigcash.blob.core.windows.net/logos-empresas/wine.jpg" },
            { "zatini", "https://bigcash.blob.core.windows.net/logos-empresas/zatini.jpg" },
            { "Aliexpress", "https://bigcash.blob.core.windows.net/logos-empresas/Aliexpress.jpeg"},
            { "Americanas", "https://bigcash.blob.core.windows.net/logos-empresas/Americanas.jpeg"},
            { "submarino", "https://bigcash.blob.core.windows.net/logos-empresas/submarino-logo-0-1536x1536.jpeg"},

        };

        public static string GetImagemPeloNome(string nome)
        {
            var imgUrl = string.Empty;

            nome = nome.ToLower().Replace("-", " ");

            if (urlLojas.Keys.Any(k => nome.Contains(k.ToLower().Replace("-", " "))))
            {
                imgUrl = urlLojas[urlLojas.Keys.First(k => nome.ToLower().Contains(k.ToLower().Replace("-", " ")))];
            }

            return imgUrl;
        }
    }
}
