//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MMN.Dominio.Excecao {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MensagemErro {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MensagemErro() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MMN.Dominio.Excecao.MensagemErro", typeof(MensagemErro).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ação não informada.
        /// </summary>
        internal static string acao_requerida {
            get {
                return ResourceManager.GetString("acao_requerida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digito da agência deve conter apenas um digito.
        /// </summary>
        internal static string agencia_digito_requisito {
            get {
                return ResourceManager.GetString("agencia_digito_requisito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O ano deve ser informado.
        /// </summary>
        internal static string ano_deve_ser_informado {
            get {
                return ResourceManager.GetString("ano_deve_ser_informado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ano inválido.
        /// </summary>
        internal static string ano_invalido {
            get {
                return ResourceManager.GetString("ano_invalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anunciante já mapeado para esta categoria.
        /// </summary>
        internal static string anunciante_categoria_mapeado {
            get {
                return ResourceManager.GetString("anunciante_categoria_mapeado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anunciante não encontrado.
        /// </summary>
        internal static string anunciante_nao_encontrado {
            get {
                return ResourceManager.GetString("anunciante_nao_encontrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sua assinatura eletônica está incorreta. Verifique e digite novamente, ou vá no menu Meus Dados e gere uma nova.
        /// </summary>
        internal static string assinatura_eletronica_incorreta {
            get {
                return ResourceManager.GetString("assinatura_eletronica_incorreta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bairro deve ser informado.
        /// </summary>
        internal static string bairro_requerido {
            get {
                return ResourceManager.GetString("bairro_requerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor insira o código de segurança.
        /// </summary>
        internal static string card_cvv {
            get {
                return ResourceManager.GetString("card_cvv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor informe o nome que consta no cartão.
        /// </summary>
        internal static string card_holder_name {
            get {
                return ResourceManager.GetString("card_holder_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor informe o número do cartão.
        /// </summary>
        internal static string card_number {
            get {
                return ResourceManager.GetString("card_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esse anunciante já está mapeado neste carrossel.
        /// </summary>
        internal static string carrossel_anunciante_mapeado {
            get {
                return ResourceManager.GetString("carrossel_anunciante_mapeado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carrossel não encontrado.
        /// </summary>
        internal static string carrossel_nao_encontrado {
            get {
                return ResourceManager.GetString("carrossel_nao_encontrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O cashback não pode ser menor que o cadastrado no estabelecimento, por favor insira um valor igual ou maior.
        /// </summary>
        internal static string cashback_menor_que_o_cadastrado {
            get {
                return ResourceManager.GetString("cashback_menor_que_o_cadastrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Percentual de cashback não pode ser maior que um.
        /// </summary>
        internal static string cashback_percentual_maximo {
            get {
                return ResourceManager.GetString("cashback_percentual_maximo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Percentual de cashback não pode ser menor ou igual a zero.
        /// </summary>
        internal static string cashback_percentual_minimo {
            get {
                return ResourceManager.GetString("cashback_percentual_minimo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Percentual de Cashback deve ser informado.
        /// </summary>
        internal static string cashback_requerido {
            get {
                return ResourceManager.GetString("cashback_requerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não é possivel excluír esta categoria pois ela possui credenciamentos mapeados à ela.
        /// </summary>
        internal static string categoria_credenciamento_mapeado {
            get {
                return ResourceManager.GetString("categoria_credenciamento_mapeado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Já existe uma categoria com este nome.
        /// </summary>
        internal static string categoria_em_uso {
            get {
                return ResourceManager.GetString("categoria_em_uso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categoria não encontrada.
        /// </summary>
        internal static string categoria_nao_encontrada {
            get {
                return ResourceManager.GetString("categoria_nao_encontrada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categoria pai está inativa.
        /// </summary>
        internal static string categoria_pai_inativa {
            get {
                return ResourceManager.GetString("categoria_pai_inativa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe o numero do celular.
        /// </summary>
        internal static string celular_requerido {
            get {
                return ResourceManager.GetString("celular_requerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cep inválido.
        /// </summary>
        internal static string cep_invalido {
            get {
                return ResourceManager.GetString("cep_invalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cidade não encontrada.
        /// </summary>
        internal static string cidade_nao_encontrada {
            get {
                return ResourceManager.GetString("cidade_nao_encontrada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comerciante não aprovado.
        /// </summary>
        internal static string comerciante_nao_aprovado {
            get {
                return ResourceManager.GetString("comerciante_nao_aprovado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comerciante não encontrado.
        /// </summary>
        internal static string comerciante_nao_encontrado {
            get {
                return ResourceManager.GetString("comerciante_nao_encontrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe o comerciante.
        /// </summary>
        internal static string comerciante_requerido {
            get {
                return ResourceManager.GetString("comerciante_requerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cadastre seu documento em meus dados antes de realizar a compra.
        /// </summary>
        internal static string compra_cadastre_dados {
            get {
                return ResourceManager.GetString("compra_cadastre_dados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe a data da compra.
        /// </summary>
        internal static string compra_data_requerida {
            get {
                return ResourceManager.GetString("compra_data_requerida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe a descrição da venda.
        /// </summary>
        internal static string compra_descricao_requerida {
            get {
                return ResourceManager.GetString("compra_descricao_requerida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe o número do pedido.
        /// </summary>
        internal static string compra_numero_requerido {
            get {
                return ResourceManager.GetString("compra_numero_requerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As compras de saldo devem ter um valor mínimo de R$10,00.
        /// </summary>
        internal static string compra_saldo_valor_minimo {
            get {
                return ResourceManager.GetString("compra_saldo_valor_minimo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe o site da compra.
        /// </summary>
        internal static string compra_site_requerido {
            get {
                return ResourceManager.GetString("compra_site_requerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aceite os termos para confirmar a compra!.
        /// </summary>
        internal static string compra_termos_requerido {
            get {
                return ResourceManager.GetString("compra_termos_requerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não é possível fazer upgrade para um produto menor ou igual ao produto ativo.
        /// </summary>
        internal static string compra_upgrade_produto_menor {
            get {
                return ResourceManager.GetString("compra_upgrade_produto_menor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor da venda deve ser maior que 0.
        /// </summary>
        internal static string compra_valor_minimo {
            get {
                return ResourceManager.GetString("compra_valor_minimo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe o valor do pedido.
        /// </summary>
        internal static string compra_valor_requerido {
            get {
                return ResourceManager.GetString("compra_valor_requerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comunicado não encontrado.
        /// </summary>
        internal static string comunicado_nao_encontrado {
            get {
                return ResourceManager.GetString("comunicado_nao_encontrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to É preciso confirmar a operação.
        /// </summary>
        internal static string confirmacao_requerida {
            get {
                return ResourceManager.GetString("confirmacao_requerida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seu consumo mensal é insuficiente para solicitar o saque.
        /// </summary>
        internal static string consumo_insuficiente {
            get {
                return ResourceManager.GetString("consumo_insuficiente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conta não encontrada.
        /// </summary>
        internal static string conta_nao_encontrada {
            get {
                return ResourceManager.GetString("conta_nao_encontrada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conta bancária deve ser selecionada.
        /// </summary>
        internal static string conta_requerida {
            get {
                return ResourceManager.GetString("conta_requerida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe o tipo de contato.
        /// </summary>
        internal static string contato_tipo_requerido {
            get {
                return ResourceManager.GetString("contato_tipo_requerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPF/CNPJ já cadastrado.
        /// </summary>
        internal static string cpf_cnpj_em_uso {
            get {
                return ResourceManager.GetString("cpf_cnpj_em_uso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe um CPF ou CNPJ válido.
        /// </summary>
        internal static string cpf_cnpj_invalido {
            get {
                return ResourceManager.GetString("cpf_cnpj_invalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não é mais possível efetuar o cadastro para este credenciamento.
        /// </summary>
        internal static string credenciamento_cadastro_expirado {
            get {
                return ResourceManager.GetString("credenciamento_cadastro_expirado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identificador do credencimento não informado.
        /// </summary>
        internal static string credenciamento_id_requerido {
            get {
                return ResourceManager.GetString("credenciamento_id_requerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seu credenciamento ainda não foi aprovado.
        /// </summary>
        internal static string credenciamento_nao_aprovado {
            get {
                return ResourceManager.GetString("credenciamento_nao_aprovado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credenciamento não encontrado!.
        /// </summary>
        internal static string credenciamento_nao_encontrado {
            get {
                return ResourceManager.GetString("credenciamento_nao_encontrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credenciamento não informado.
        /// </summary>
        internal static string credenciamento_nao_informado {
            get {
                return ResourceManager.GetString("credenciamento_nao_informado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credenciamento já recebido.
        /// </summary>
        internal static string credenciamento_recebido {
            get {
                return ResourceManager.GetString("credenciamento_recebido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seu credenciamento foi reprovado.
        /// </summary>
        internal static string credenciamento_reprovado {
            get {
                return ResourceManager.GetString("credenciamento_reprovado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apenas comerciantes podem criar cupons.
        /// </summary>
        internal static string cupon_nao_comerciante {
            get {
                return ResourceManager.GetString("cupon_nao_comerciante", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token com dígito verificador inválido.
        /// </summary>
        internal static string cupon_token_digito_invalido {
            get {
                return ResourceManager.GetString("cupon_token_digito_invalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token deve ser informado.
        /// </summary>
        internal static string cupon_token_requerido {
            get {
                return ResourceManager.GetString("cupon_token_requerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data de expiração é invalida.
        /// </summary>
        internal static string data_expiracao_invalido {
            get {
                return ResourceManager.GetString("data_expiracao_invalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data fim deve ser informada.
        /// </summary>
        internal static string data_fim_requerida {
            get {
                return ResourceManager.GetString("data_fim_requerida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data inicial deve ser menor que data final.
        /// </summary>
        internal static string data_inicial_final {
            get {
                return ResourceManager.GetString("data_inicial_final", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data inicio deve ser informada.
        /// </summary>
        internal static string data_inicio_requerida {
            get {
                return ResourceManager.GetString("data_inicio_requerida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utilize e-mail com: \&quot;.com\&quot;, \&quot;.com.br\&quot;.
        /// </summary>
        internal static string email_com_br {
            get {
                return ResourceManager.GetString("email_com_br", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmação de email deve ser informada.
        /// </summary>
        internal static string email_confirmacao_requerida {
            get {
                return ResourceManager.GetString("email_confirmacao_requerida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email já em uso.
        /// </summary>
        internal static string email_em_uso {
            get {
                return ResourceManager.GetString("email_em_uso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Inválido.
        /// </summary>
        internal static string email_invalido {
            get {
                return ResourceManager.GetString("email_invalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email e confirmação de email não coincidem.
        /// </summary>
        internal static string email_nao_confere {
            get {
                return ResourceManager.GetString("email_nao_confere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sua conta ainda não está ativa pois o email de validação ainda não foi confirmado. Clique em confirmar no seu email para ativar sua conta. Verifique sua caixa de entrada e spam.
        /// </summary>
        internal static string email_nao_confirmado {
            get {
                return ResourceManager.GetString("email_nao_confirmado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail inválido - Não são permitidos emails contendo: \&quot;.gov\&quot;, \&quot;.gov.br\&quot;, \&quot;hotmail.com\&quot;, \&quot;msn.com\&quot;, \&quot;yahoo.com\&quot;, \&quot;yahoo.com.br\&quot;, \&quot;globo.com\&quot;, \&quot;icloud.com\&quot;.
        /// </summary>
        internal static string email_nao_permitido {
            get {
                return ResourceManager.GetString("email_nao_permitido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email deve ser informado.
        /// </summary>
        internal static string email_requerido {
            get {
                return ResourceManager.GetString("email_requerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail inválido - E-mails devem conter &apos;@&apos; e terminarem com &apos;.com&apos; ou &apos;.com.br&apos;.
        /// </summary>
        internal static string email_requisito {
            get {
                return ResourceManager.GetString("email_requisito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preencha o endereço do empreendedor.
        /// </summary>
        internal static string empreendedor_sem_endereco {
            get {
                return ResourceManager.GetString("empreendedor_sem_endereco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Já existe um estabelecimento com este nome cadastrado com esta categoria.
        /// </summary>
        internal static string estabelecimento_em_uso {
            get {
                return ResourceManager.GetString("estabelecimento_em_uso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estabelecimento deve ser informado.
        /// </summary>
        internal static string estabelecimento_requerido {
            get {
                return ResourceManager.GetString("estabelecimento_requerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Você já tem uma fatura aberta. Após seu pagamento será possível gerar uma nova.
        /// </summary>
        internal static string fatura_em_pagamento {
            get {
                return ResourceManager.GetString("fatura_em_pagamento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fatura não encontrada.
        /// </summary>
        internal static string fatura_nao_encontrada {
            get {
                return ResourceManager.GetString("fatura_nao_encontrada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pelo menos uma graduação deve ser adicionada.
        /// </summary>
        internal static string graduacao_requerida {
            get {
                return ResourceManager.GetString("graduacao_requerida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IdMensagem deve ser informada.
        /// </summary>
        internal static string idmensagem_requerida {
            get {
                return ResourceManager.GetString("idmensagem_requerida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imagem inválida, resolução permitida: 320x320.
        /// </summary>
        internal static string imagem_app_resolucao_maxima {
            get {
                return ResourceManager.GetString("imagem_app_resolucao_maxima", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imagem requirida!.
        /// </summary>
        internal static string imagem_requerida {
            get {
                return ResourceManager.GetString("imagem_requerida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe para qual plano será feito o upgrade.
        /// </summary>
        internal static string informe_plano_upgrade {
            get {
                return ResourceManager.GetString("informe_plano_upgrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latitude deve ser informada.
        /// </summary>
        internal static string latitude_requerida {
            get {
                return ResourceManager.GetString("latitude_requerida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não é permitido trocar o login mais de uma vez.
        /// </summary>
        internal static string login_alterado {
            get {
                return ResourceManager.GetString("login_alterado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login bloqueado.
        /// </summary>
        internal static string login_bloqueado {
            get {
                return ResourceManager.GetString("login_bloqueado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login com caractéres inválidos, só são permitido letras e números.
        /// </summary>
        internal static string login_caracteres_invalidos {
            get {
                return ResourceManager.GetString("login_caracteres_invalidos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login já em uso.
        /// </summary>
        internal static string login_em_uso {
            get {
                return ResourceManager.GetString("login_em_uso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário ou Senha incorreto.
        /// </summary>
        internal static string login_incorreto {
            get {
                return ResourceManager.GetString("login_incorreto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foi atingido o limite de tentativas de login incorretas.
        /// </summary>
        internal static string login_limite_tentativa {
            get {
                return ResourceManager.GetString("login_limite_tentativa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não são permitidos logins contendo: \&quot;bigcash\&quot;, \&quot;bigcashme\&quot;, \&quot;cashme\&quot;, \&quot;big\&quot;, \&quot;cash\&quot;, \&quot;admin\&quot;, \&quot;admins\&quot;.
        /// </summary>
        internal static string login_nao_permitido {
            get {
                return ResourceManager.GetString("login_nao_permitido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login deve ser informado.
        /// </summary>
        internal static string login_requerido {
            get {
                return ResourceManager.GetString("login_requerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login deve conter no mínimo 5 caracteres.
        /// </summary>
        internal static string login_tamanho_minimo {
            get {
                return ResourceManager.GetString("login_tamanho_minimo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logo deve ser informada.
        /// </summary>
        internal static string logo_requerida {
            get {
                return ResourceManager.GetString("logo_requerida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logo inválida, resolução máxima permitida: 1024x1024.
        /// </summary>
        internal static string logo_resolucao_maxima {
            get {
                return ResourceManager.GetString("logo_resolucao_maxima", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Longitude deve ser informada.
        /// </summary>
        internal static string longitude_requerida {
            get {
                return ResourceManager.GetString("longitude_requerida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mensagem ou imagem deve ser preenchida.
        /// </summary>
        internal static string mensagem_imagem_nao_preenchida {
            get {
                return ResourceManager.GetString("mensagem_imagem_nao_preenchida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mensagem não encontrada.
        /// </summary>
        internal static string mensagem_nao_encontrada {
            get {
                return ResourceManager.GetString("mensagem_nao_encontrada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe a Mensagem.
        /// </summary>
        internal static string mensagem_requerida {
            get {
                return ResourceManager.GetString("mensagem_requerida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mês inválido.
        /// </summary>
        internal static string mes_invalido {
            get {
                return ResourceManager.GetString("mes_invalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe o Nome.
        /// </summary>
        internal static string nome_requerido {
            get {
                return ResourceManager.GetString("nome_requerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anexe a nota fiscal!.
        /// </summary>
        internal static string nota_fiscal_requerida {
            get {
                return ResourceManager.GetString("nota_fiscal_requerida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número deve ser informado.
        /// </summary>
        internal static string numero_requerido {
            get {
                return ResourceManager.GetString("numero_requerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe a observação.
        /// </summary>
        internal static string observacao_requerida {
            get {
                return ResourceManager.GetString("observacao_requerida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forma de pagamento ainda não implementada.
        /// </summary>
        internal static string pagamanto_tipo_nao_implementado {
            get {
                return ResourceManager.GetString("pagamanto_tipo_nao_implementado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecione um tipo de pagamento válido.
        /// </summary>
        internal static string pagamento_tipo_invalido {
            get {
                return ResourceManager.GetString("pagamento_tipo_invalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecione o tipo de pagamento.
        /// </summary>
        internal static string pagamento_tipo_requirido {
            get {
                return ResourceManager.GetString("pagamento_tipo_requirido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor pago insuficiente.
        /// </summary>
        internal static string pagamento_valor_insuficiente {
            get {
                return ResourceManager.GetString("pagamento_valor_insuficiente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Já existe um parceiro cadastrado com este nome.
        /// </summary>
        internal static string parceiro_nome_em_uso {
            get {
                return ResourceManager.GetString("parceiro_nome_em_uso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Já existe um parceiro cadastrado com este número.
        /// </summary>
        internal static string parceiro_numero_em_uso {
            get {
                return ResourceManager.GetString("parceiro_numero_em_uso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parcela inativa.
        /// </summary>
        internal static string parcela_inativa {
            get {
                return ResourceManager.GetString("parcela_inativa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esta parcela não pode ser alterada.
        /// </summary>
        internal static string parcela_nao_editavel {
            get {
                return ResourceManager.GetString("parcela_nao_editavel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parcela já foi paga.
        /// </summary>
        internal static string parcela_paga {
            get {
                return ResourceManager.GetString("parcela_paga", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patrocinador inativo.
        /// </summary>
        internal static string patrocinador_inativo {
            get {
                return ResourceManager.GetString("patrocinador_inativo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patrocinador não encontrado.
        /// </summary>
        internal static string patrocinador_nao_encontrado {
            get {
                return ResourceManager.GetString("patrocinador_nao_encontrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe o Patrocinador.
        /// </summary>
        internal static string patrocinador_requerido {
            get {
                return ResourceManager.GetString("patrocinador_requerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pedido já efetuado.
        /// </summary>
        internal static string pedido_duplicado {
            get {
                return ResourceManager.GetString("pedido_duplicado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pedido inativo.
        /// </summary>
        internal static string pedido_inativo {
            get {
                return ResourceManager.GetString("pedido_inativo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pedido não encontrado.
        /// </summary>
        internal static string pedido_nao_encontrado {
            get {
                return ResourceManager.GetString("pedido_nao_encontrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pedido está pago.
        /// </summary>
        internal static string pedido_pago {
            get {
                return ResourceManager.GetString("pedido_pago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pedido não possui nenhum pagamento válido.
        /// </summary>
        internal static string pedido_sem_pagamento {
            get {
                return ResourceManager.GetString("pedido_sem_pagamento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pedido ainda não tem transação!.
        /// </summary>
        internal static string pedido_sem_transacao {
            get {
                return ResourceManager.GetString("pedido_sem_transacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pedido possui apenas uma parcela ainda não paga.
        /// </summary>
        internal static string pedido_unica_parcela_nao_paga {
            get {
                return ResourceManager.GetString("pedido_unica_parcela_nao_paga", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Só é possivel remover parcelas de pedidos que possuam pelo menos duas parcelas não pagas.
        /// </summary>
        internal static string pedido_unica_parcela_nao_paga_remover {
            get {
                return ResourceManager.GetString("pedido_unica_parcela_nao_paga_remover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plano inválido.
        /// </summary>
        internal static string plano_invalido {
            get {
                return ResourceManager.GetString("plano_invalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Para continuar é necessário aceitar a politica de privacidade acessando seu &apos;Escritório Virtual&apos;.
        /// </summary>
        internal static string politica_escritorio_requerida {
            get {
                return ResourceManager.GetString("politica_escritorio_requerida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Produto deve ser fornecido.
        /// </summary>
        internal static string produto_requerido {
            get {
                return ResourceManager.GetString("produto_requerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Motivo da recusa deve ser informado.
        /// </summary>
        internal static string recusa_motivo_requerido {
            get {
                return ResourceManager.GetString("recusa_motivo_requerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não é possível remover uma compra processada ou finalizada.
        /// </summary>
        internal static string remover_compra_status {
            get {
                return ResourceManager.GetString("remover_compra_status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Este não é um pedido de compra.
        /// </summary>
        internal static string remover_compra_tipo {
            get {
                return ResourceManager.GetString("remover_compra_tipo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rua deve ser informada.
        /// </summary>
        internal static string rua_requerida {
            get {
                return ResourceManager.GetString("rua_requerida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saldo insuficiente.
        /// </summary>
        internal static string saldo_insuficiente {
            get {
                return ResourceManager.GetString("saldo_insuficiente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecione os saques que deseja executar a ação.
        /// </summary>
        internal static string saque_selecao_requerida {
            get {
                return ResourceManager.GetString("saque_selecao_requerida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor deve ser maior que 100.
        /// </summary>
        internal static string saque_valor_minimo {
            get {
                return ResourceManager.GetString("saque_valor_minimo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sem permissão para efetuar esta ação.
        /// </summary>
        internal static string sem_permissao {
            get {
                return ResourceManager.GetString("sem_permissao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O token para alterar a senha expirou.
        /// </summary>
        internal static string senha_alterar_token_expirado {
            get {
                return ResourceManager.GetString("senha_alterar_token_expirado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senha incorreta.
        /// </summary>
        internal static string senha_incorreta {
            get {
                return ResourceManager.GetString("senha_incorreta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senhas não conferem!.
        /// </summary>
        internal static string senha_nao_confere {
            get {
                return ResourceManager.GetString("senha_nao_confere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senha deve conter no mínimo 8 caracteres sendo pelo menos 1 número e 1 letra.
        /// </summary>
        internal static string senha_requisitos {
            get {
                return ResourceManager.GetString("senha_requisitos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não é possível enviar solicitações deste tipo no momento.
        /// </summary>
        internal static string solicitacao_indisponivel {
            get {
                return ResourceManager.GetString("solicitacao_indisponivel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Já existe uma solicitação pendente!.
        /// </summary>
        internal static string solicitacao_pendente_existe {
            get {
                return ResourceManager.GetString("solicitacao_pendente_existe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe o novo status.
        /// </summary>
        internal static string status_novo_requerido {
            get {
                return ResourceManager.GetString("status_novo_requerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não é possivel criar esta sub categoria.
        /// </summary>
        internal static string sub_categoria_nao_permitida {
            get {
                return ResourceManager.GetString("sub_categoria_nao_permitida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taxa incorreta. Recarregue a página e tente novamente.
        /// </summary>
        internal static string taxa_incorreta {
            get {
                return ResourceManager.GetString("taxa_incorreta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número de telefone já em uso.
        /// </summary>
        internal static string telefone_em_uso {
            get {
                return ResourceManager.GetString("telefone_em_uso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Celular inválido.
        /// </summary>
        internal static string telefone_invalido {
            get {
                return ResourceManager.GetString("telefone_invalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefone deve ser informado.
        /// </summary>
        internal static string telefone_requerido {
            get {
                return ResourceManager.GetString("telefone_requerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Titulo deve ser preenchido.
        /// </summary>
        internal static string titulo_requerido {
            get {
                return ResourceManager.GetString("titulo_requerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token com erro ou expirou. Faça o login novamente.
        /// </summary>
        internal static string token_erro {
            get {
                return ResourceManager.GetString("token_erro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O Token expirou.
        /// </summary>
        internal static string token_invalido {
            get {
                return ResourceManager.GetString("token_invalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token com dígito verificador inválido.
        /// </summary>
        internal static string token_venda_digito_invalido {
            get {
                return ResourceManager.GetString("token_venda_digito_invalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Já existe um token com o código enviado.
        /// </summary>
        internal static string token_venda_duplicado {
            get {
                return ResourceManager.GetString("token_venda_duplicado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token invalido.
        /// </summary>
        internal static string token_venda_invalido {
            get {
                return ResourceManager.GetString("token_venda_invalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apenas comerciantes podem criar vendas.
        /// </summary>
        internal static string token_venda_nao_comerciante {
            get {
                return ResourceManager.GetString("token_venda_nao_comerciante", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token não encontrado.
        /// </summary>
        internal static string token_venda_nao_encontrado {
            get {
                return ResourceManager.GetString("token_venda_nao_encontrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token deve ser informado.
        /// </summary>
        internal static string token_venda_requerido {
            get {
                return ResourceManager.GetString("token_venda_requerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Este token de venda já foi resgatado.
        /// </summary>
        internal static string token_venda_resgatado {
            get {
                return ResourceManager.GetString("token_venda_resgatado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário bloqueado.
        /// </summary>
        internal static string usuario_bloqueado {
            get {
                return ResourceManager.GetString("usuario_bloqueado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário inativo.
        /// </summary>
        internal static string usuario_inativo {
            get {
                return ResourceManager.GetString("usuario_inativo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário inválido.
        /// </summary>
        internal static string usuario_invalido {
            get {
                return ResourceManager.GetString("usuario_invalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário não encontrado!.
        /// </summary>
        internal static string usuario_nao_encontrado {
            get {
                return ResourceManager.GetString("usuario_nao_encontrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário já possui outro pedido em aberto.
        /// </summary>
        internal static string usuario_pedido_aberto {
            get {
                return ResourceManager.GetString("usuario_pedido_aberto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não é possivel acessar o usuário remotamente antes do e-mail ser cofirmado.
        /// </summary>
        internal static string usuario_remoto_email_confirmado {
            get {
                return ResourceManager.GetString("usuario_remoto_email_confirmado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário sem endereço cadastrado.
        /// </summary>
        internal static string usuario_sem_endereco {
            get {
                return ResourceManager.GetString("usuario_sem_endereco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor final deve ser maior que zero.
        /// </summary>
        internal static string valor_final_minimo {
            get {
                return ResourceManager.GetString("valor_final_minimo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor inicial deve ser menor que valor final.
        /// </summary>
        internal static string valor_inicial_final {
            get {
                return ResourceManager.GetString("valor_inicial_final", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor inicial deve ser maior que 0.
        /// </summary>
        internal static string valor_inicial_minimo {
            get {
                return ResourceManager.GetString("valor_inicial_minimo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor da venda deve ser maior que R$1,00.
        /// </summary>
        internal static string venda_valor_minimo_1 {
            get {
                return ResourceManager.GetString("venda_valor_minimo_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verifique os campos e tente novamente.
        /// </summary>
        internal static string verifique_campos {
            get {
                return ResourceManager.GetString("verifique_campos", resourceCulture);
            }
        }
    }
}
