//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MMN.Dominio.Excecao {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MensagemErroInterno {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MensagemErroInterno() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MMN.Dominio.Excecao.MensagemErroInterno", typeof(MensagemErroInterno).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não foi possível executar a operação..
        /// </summary>
        internal static string erro_interno {
            get {
                return ResourceManager.GetString("erro_interno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loja não encontrada!.
        /// </summary>
        internal static string GET__Anunciante_gerarUrl {
            get {
                return ResourceManager.GetString("GET /Anunciante/gerarUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro ao obter dados..
        /// </summary>
        internal static string GET__Extrato_obterLancamentos {
            get {
                return ResourceManager.GetString("GET /Extrato/obterLancamentos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro ao obter saldos..
        /// </summary>
        internal static string GET__Extrato_obterSaldoPorTipo {
            get {
                return ResourceManager.GetString("GET /Extrato/obterSaldoPorTipo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro ao buscar a taxa de compra.
        /// </summary>
        internal static string GET__Pedidos_taxaSaldo {
            get {
                return ResourceManager.GetString("GET /Pedidos/taxaSaldo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro ao atualizar usuário!.
        /// </summary>
        internal static string POST__Admin_editarDadosUsuario {
            get {
                return ResourceManager.GetString("POST /Admin/editarDadosUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro ao ativar plano..
        /// </summary>
        internal static string POST__Admin_UpgradeManual {
            get {
                return ResourceManager.GetString("POST /Admin/UpgradeManual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro ao ativar plano..
        /// </summary>
        internal static string POST__Admin_UpgradePresente {
            get {
                return ResourceManager.GetString("POST /Admin/UpgradePresente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro ao atualizar usuário!.
        /// </summary>
        internal static string POST__Usuario_atualizarDadosUsuario {
            get {
                return ResourceManager.GetString("POST /Usuario/atualizarDadosUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro ao atualizar usuário!.
        /// </summary>
        internal static string POST__Usuario_editarUsuario {
            get {
                return ResourceManager.GetString("POST /Usuario/editarUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro em Atualizar Assinatura Eletrônica!.
        /// </summary>
        internal static string POST__Usuario_updateAssinaturaEletronica {
            get {
                return ResourceManager.GetString("POST /Usuario/updateAssinaturaEletronica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro em Atualizar Imgem!.
        /// </summary>
        internal static string POST__Usuario_updateImage {
            get {
                return ResourceManager.GetString("POST /Usuario/updateImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro ao cadastrar banco!.
        /// </summary>
        internal static string POST__UsuarioBanco_cadastrarUsuarioBanco {
            get {
                return ResourceManager.GetString("POST /UsuarioBanco/cadastrarUsuarioBanco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro ao alterar senha!.
        /// </summary>
        internal static string POST__UsuarioLogin_alterarSenha {
            get {
                return ResourceManager.GetString("POST /UsuarioLogin/alterarSenha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro ao Atualizar Endereço!.
        /// </summary>
        internal static string PUT__UsuarioEndereco_editarUsuarioEndereco {
            get {
                return ResourceManager.GetString("PUT /UsuarioEndereco/editarUsuarioEndereco", resourceCulture);
            }
        }
    }
}
